from fastapi import FastAPI
from fastapi import HTTPException
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from llm import OpenAIService

app = FastAPI()
openai_service = OpenAIService()

#Generated by ChatGPT ===========
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  # ✅ Allows frontend to access the backend
    allow_credentials=True,
    allow_methods=["*"],  # ✅ Allows GET, POST, OPTIONS, DELETE, etc.
    allow_headers=["*"],  # ✅ Allows all headers (needed for Axios)
)
#==================================

class PromptInput(BaseModel):
    prompt: str

class TextInput(BaseModel):
    text:str
@app.get("/")
def read_root():
    return {"message": "Hello, FastAPI!"}

@app.post("/generated")
def generate_text(input_data: TextInput):
    generated_text = openai_service.generate_text(input_data.prompt)
    return {"generated_text": generated_text}

@app.post("/process-text")
def process_text(input_data: TextInput):
    generated_text = openai_service.generate_text(input_data.text)
   #process_text = f"Recieved: {input_data.text}"
    return {"processed_text": generated_text}

#
@app.post("/agent1")
def text_agent1(input_data: TextInput):
    text_agent1 = openai_service.agent1(input_data.text)
   #process_text = f"Recieved: {input_data.text}"
    return {"processed_text": text_agent1}